"""create chat sessions and messages tables

Revision ID: a1b2c3d4e5f6
Revises: 195186c1ee05
Create Date: 2026-08-30 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '195186c1ee05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create chat_sessions table
    op.create_table(
        'chat_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_chat_sessions_id'),
        'chat_sessions',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_chat_sessions_case_id'),
        'chat_sessions',
        ['case_id'],
        unique=False,
    )

    # Create chat_messages table
    op.create_table(
        'chat_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['session_id'],
            ['chat_sessions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_chat_messages_id'),
        'chat_messages',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_chat_messages_session_id'),
        'chat_messages',
        ['session_id'],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f('ix_chat_messages_session_id'),
        table_name='chat_messages',
    )
    op.drop_index(
        op.f('ix_chat_messages_id'),
        table_name='chat_messages',
    )
    op.drop_table('chat_messages')

    op.drop_index(
        op.f('ix_chat_sessions_case_id'),
        table_name='chat_sessions',
    )
    op.drop_index(
        op.f('ix_chat_sessions_id'),
        table_name='chat_sessions',
    )
    op.drop_table('chat_sessions')

    # ### end Alembic commands ###
